name: Daily Llamafile Update (Multi-Repo)

on:
  schedule:
    - cron:  '0 0 * * *'  # Runs every day at 12 AM
  workflow_dispatch:  # Enables manual triggering

jobs:
  update-llamafiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Define repositories (optional)
        id: define_repos
        if: github.event.inputs.repos == ''
        run: |
          # Define repositories as comma-separated values (optional)
          # Example: REPOSITORIES="huggingface/repo1,your-org/repo2"
          export REPOSITORIES="Qwen/Qwen1.5-MoE-A2.7B"
          echo "::set-output name=REPOSITORIES::${{ secrets.REPOSITORIES }}"

      - name: Define repositories from workflow dispatch
        id: define_repos_dispatch
        if: steps.define_repos.outputs.REPOSITORIES == ''
        run: |
          REPOSITORIES=${{ github.event.inputs.repos }}
          echo "::set-output name=REPOSITORIES::$REPOSITORIES"

      - name: Install zipalign
        run: |
          sudo apt-get update && sudo apt-get install zipalign

      - name: Fetch latest commits with .gguf files
        uses: actions/github-script@v6  # Use the action for script execution
        with:
          script: |
            const octokit = require('@octokit/rest');
            const github = new octokit({ token: core.secrets.GITHUB_TOKEN });
            const repos = core.getInput('REPOSITORIES').split(',');

            async function getCommits(repo) {
              const [owner, repoName] = repo.split('/');
              const { data: commits } = await github.repos.listCommits({
                owner,
                repo: repoName,
                sha: 'master',  # You can also specify a specific branch if needed
              });
              return commits.filter(commit => commit.sha.endsWith('.gguf'));
            }

            async function main() {
              const allCommits = [];
              for (const repo of repos) {
                const commits = await getCommits(repo);
                allCommits.push(...commits);
              }
              core.setOutput('commits', JSON.stringify(allCommits));
            }

            main().catch(error => core.setFailed(error.message));

      - name: Set COMMITS variable
        run: |
          echo "::set-output name=COMMITS::${{ steps.fetch-latest-commits.outputs.commits }}"

      - name: Download .gguf files
        uses: actions/download-artifact@v3
        with:
          name: ${{ steps.get_commits.outputs.COMMITS }}  # No jsonPath call

      - name: Convert .gguf files to llamafiles
        run: |
          today=$(date +"%d-%m-%Y")

          for commit in ${{ steps.get_commits.outputs.COMMITS }}; do
              repo_name=$(echo "$commit" | cut -d'/' -f2)
              mkdir -p "$today/$repo_name"

              for file in ./gguf_files/$commit/*.gguf; do
                  filename=$(basename "$file")
                  llamafile_name="${filename%.gguf}.llamafile"

                  zipalign -j0 "$file" "$llamafile_name"
                  mv "$llamafile_name" "$today/$repo_name"
              done
          done

      - name: Delete old llamafiles (optional)
        run: |
          rm -rf *  # Delete all llamafiles outside of the newly created folders

      - name: Commit changes (optional)
        uses: actions/checkout@v3

      - name: Add and commit changes
        run: |
          git add .
          git commit -m "Update llamafiles from latest commits on $today"

      # Consider using actions/checkout@v3 with 'with' input for pushing if needed
      - name: Push changes (optional)
        uses: actions/checkout@v3
        with:
          fetch: true  # Optional, fetch latest changes before pushing
        run: |
          git push origin master  # Replace with your branch name if needed
